#!/usr/bin/env bash
cd bin
. imports.sh "$@"
cd ..

echo "This script will make setup"
if [[ -e "PACKAGE" ]]
then
    full_package_name="$(<PACKAGE)"
else
    package_owner="dralec"
    package_name="moomba"
    package_description="PHP Library"

    read -e -p "Enter package owner [${package_owner}]: " input
    package_owner="${input:-$package_owner}"
    read -e -i "$package_name" -p "Enter package name: " input
    package_name="${input:-$package_owner}"
    read -e -i "$package_description" -p "Enter package description: " input
    package_description="${input:-$package_description}"
    package_namespace="${package_name^}"
#    package_namespace="DefaultNamespace"
    read -e -p "Enter package namespace [${package_namespace}]: " input
    package_namespace="${input:-$package_namespace}"
fi
echo "Creating php package: ${package_owner}/${package_name}"
echo "Description: ${package_description}"
echo "Namespace: ${package_namespace}"


read -p "Continue? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    sed "s/PACKAGE_OWNER/${package_owner}/g; s/PACKAGE_NAME/${package_name}/g; s/PACKAGE_DESCRIPTION/${package_description}/g; s/PACKAGE_NSPACE/${package_namespace}/g;" composer.json.template | tee composer.json.result
    cat composer.json.result

    user=$(whoami)
    u_id="$(id -u ${user})"
    g_id="$(id -g ${user})"
    if [[ -e "${ENV_FILE}" ]]
    then
        echo "Removing .env file"
        rm .env
    fi
    echo "Creating .env file"
    touch .env
    echo "USER_ID=${u_id}" >> .env
    echo "GROUP_ID=${u_id}" >> .env
    if [[ -e ".gitattributes.dist" ]]
    then
        echo "Creating .gitattributes file"
        mv .gitattributes.dist .gitattributes
    else
        if [[ -e ".gitattributes" ]]
        then
            echo ".gitattributes file already exists"
        else
            echo ".gitattributes file not found"
        fi
    fi

    echo "Deleting setup script"
#    mv setup setup.done
else
    echo "Skip setup"
    echo
fi
